/* eslint-disable @next/next/no-head-element */
import '@/styles/globals.css';

import { FC } from 'react';

import { CommonProps } from '@/types/common';


const HomeLayout: FC<CommonProps> = ({ children }) => (
    <html>
        <head>
            <title>B2B Assistant</title>
            {/* <meta name="description" content="Generated by create next app" /> */}
            <link rel="icon" href="/favicon.ico" />
        </head>
        <body>
            {children}
        </body>
    </html>
);

export default HomeLayout;
